---
name: Build and push to Docker Hub


on:
  push:
    branches:
      - main
 

jobs:
  build-image:
    name: Build Image
    runs-on: arm64v8/debian:bullseye  
    steps:
            
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: asenasenov/photometry-arm64:latest
